all: solucion1 solucion2 solucion3 

clean:
	rm -f solucion1 solucion2 solucion3

solucion1: solucion1.c
	gcc -o solucion1 solucion1.c -Wall

solucion2: solucion2.c
	gcc -o solucion2 solucion2.c -Wall

solucion3: solucion3.c
	gcc -o solucion3 solucion3.c -Wall
